### ISSUE TITLE
[Enhancement] Display function outline to the right underneath Module Docs

### ISSUE THREAD

**Issue by bbkane** [dmy/elm-package-info#10]
It would be very useful to me if I could see all the functions available in this module (similar to how I can see all the modules in this package). I think a section underneath Module docs would make it fit nicely, but I'm not a designer :)

Thank you for this webextension! Glad I saw it on Slack.

**Comment by rlefevre** [comment]
It could be nice, but I see too much issues to do it in the browser extension:
1. Currently, when you search some function in the search box, the functions are then listed under each module, so this would be the logical place to display available functions with an empty search. However because of the virtual DOM, the web extensions cannot reliably modify existing DOM nodes of the page, everything is done in a distinct node at the end of `body`.
2. Some packages have a lot of functions per module (for example elm/core or ianmackenzie/elm-geometry), this would make other important information displayed by the extension like the install command or elm version less accessible, unless the functions are listed under which would be awkward.
3. This would require to download and parse again the documentation of the module, which is already done by the page, so this would waste resources.

Overall, I think that this would require a proper modification of the web site itself to be done properly, so I don't intend to add it to the extension for now.

**Comment by bbkane** [comment]
Okay, thank you!
